name: stringx for R (ICU bundle; ubuntu-latest)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y upgrade
        sudo apt-get -y install libcurl4-openssl-dev r-base-dev devscripts libicu-dev language-pack-pl
        sudo Rscript -e "install.packages('stringi', configure.args='--disable-pkg-config')"
        sudo Rscript -e "install.packages('realtest')"
    - name: Install stringx
      run: |
        LC_ALL="pl_PL.UTF-8" sudo R CMD INSTALL .
    - name: Test stringx
      run: |
        sudo Rscript -e 'source(".devel/realtest.R")'
        LC_ALL="pl_PL.UTF-8" Rscript -e 'source(".devel/realtest.R")'
        LC_ALL="C" Rscript -e 'source(".devel/realtest.R")'
